name: cafeteria
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations: # ← ADDED
    sdk: flutter               # ← ADDED

  equatable: ^2.0.8
  dartz: ^0.10.1
  get_it: ^8.0.0
  dio: ^5.7.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.3.2
  aad_oauth: ^1.0.1
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  mocktail: ^1.0.4
  animate_do: ^4.2.0
  firebase_core: ^4.7.0
  firebase_messaging: ^16.2.0
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "assets/icons/logo.png"
  adaptive_icon_foreground: "assets/icons/logo.png"
  image_path_ios: "assets/icons/logo.png"

flutter:
  generate: true               # ← ADDED (enables flutter gen-l10n codegen)

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/